

development:
  adapter: postgresql
  encoding: unicode
  database: smallbook
  pool: 5
  username: kenny
  password: toaster
  host: :localhost



test:
  adapter: postgresql
  encoding: unicode
  database: smallbook_test
  pool: 5
  username: kenny
  password: toaster
